services:
  mcp-server:
    build:
      context: ./mcp-server
    # so i can call localhost:9090/mcp on openwebui
    network_mode: host
    depends_on:
    - frr
    restart: always
  frr: 
    image: frrouting/frr:v8.4.0
    network_mode: host
    privileged: true
    # add future feature: persis frr config
    # volumes:
    # - ./frr:/frr
    restart: always
  open-webui: 
    image: openwebui/open-webui
    # the containter needs to access ollama API
    network_mode: host
    volumes:
    - ./open-webui:/app/backend/data
    depends_on:
    - mcp-server
    restart: always

volumes:
  open-webui:
