services:
  mcp-server:
    build:
      context: ./mcp-server
    network_mode: host
    depends_on:
    - frr
    restart: always
  frr: 
    build:
      context: ./frr
    # network_mode: host
    privileged: true
    container_name: frr-router-1
    ports:
      - "2323:23"
    # add future feature: persis frr config
    # volumes:
    # - ./frr:/frr
    restart: always
  open-webui: 
    image: openwebui/open-webui
    # the containter needs to access ollama API
    network_mode: host
    volumes:
    - ./open-webui:/app/backend/data
    depends_on:
    - mcp-server
    restart: always

volumes:
  open-webui:
